apiVersion: v1
kind: Service
metadata:
  name: restaurant-app-service
  namespace: restaurant-app
spec:
  selector:
    app: restaurant-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

